import { citiesColombia } from "./co.js";
export const data = {
  countries: [
    {
      iso2: "AR",
      iso3: "ARG",
      country: "Argentina",
      currency: "ARS",
      symbol: "$",
      cities: [
        "28 de Noviembre",
        "Abasto",
        "Acassuso",
        "Acebal",
        "Acevedo",
        "Adelia Maria",
        "Agua de Oro",
        "Albardon",
        "Albarellos",
        "Alberdi",
        "Alberti",
        "Aldo Bonzi",
        "Alejandro Korn",
        "Alicia",
        "Allen",
        "Almafuerte",
        "Almagro",
        "Almirante Brown",
        "Alta Gracia",
        "Alta Italia",
        "Alvarez",
        "Alvear",
        "Anatuya",
        "Angelica",
        "Antonio Carboni",
        "Apostoles",
        "Arequito",
        "Armstrong",
        "Arrecifes",
        "Arroyito",
        "Arroyito Challaco",
        "Arroyo Seco",
        "Arteaga",
        "Asamblea",
        "Ascension",
        "Avellaneda",
        "Ayacucho",
        "Azara",
        "Azul",
        "Balcarce",
        "Balnearia",
        "Banda del Rio Sali",
        "Bandera",
        "Banfield",
        "Baradero",
        "Bariloche",
        "Barrio Fisherton",
        "Batan",
        "Beccar",
        "Belen de Escobar",
        "Belgrano",
        "Bell Ville",
        "Bella Vista",
        "Benavidez",
        "Berazategui",
        "Berisso",
        "Bernal",
        "Bernardo Larroude",
        "Bernasconi",
        "Bigand",
        "Bombal",
        "Bordenave",
        "Bosch",
        "Bosques",
        "Boulogne",
        "Bovril",
        "Bragado",
        "Brandsen",
        "Brinkmann",
        "Buenos Aires",
        "Burzaco",
        "Bustinza",
        "Caballito",
        "Calderon",
        "Caleta Olivia",
        "Caleufu",
        "Camilo Aldao",
        "Campana",
        "Canada de Gomez",
        "Canada del Ucle",
        "Canada Rosquin",
        "Canals",
        "Canning",
        "Canuelas",
        "Capilla del Monte",
        "Capilla del Senor",
        "Capitan Bermudez",
        "Carhue",
        "Carlos Casares",
        "Carlos Pellegrini",
        "Carlos Tejedor",
        "Caseros",
        "Casilda",
        "Castelar",
        "Castelli",
        "Castillo",
        "Catriel",
        "Catrilo",
        "Cavanagh",
        "Centenario",
        "Ceres",
        "Cervantes",
        "Chacabuco",
        "Chacarita",
        "Chajari",
        "Charata",
        "Chateaubriand",
        "Chilecito",
        "Chivilcoy",
        "Choele Choel",
        "Chorroarin",
        "Cinco Saltos",
        "Cipolletti",
        "City Bell",
        "Ciudad General Belgrano",
        "Ciudadela",
        "Claypole",
        "Clorinda",
        "Colon",
        "Colonia Baron",
        "Colonia Caroya",
        "Colonia San Miguel Arcangel",
        "Comodoro Rivadavia",
        "Concepcion",
        "Concordia",
        "Constituyentes",
        "Coronel Dorrego",
        "Coronel Martinez de Hoz",
        "Coronel Pringles",
        "Corral de Bustos",
        "Corralitos",
        "Corrientes",
        "Cosquin",
        "Coy Aike",
        "Cramer",
        "Crespo",
        "Cruz del Eje",
        "Curuzu Cuatia",
        "Cutral-Co",
        "Darregueira",
        "De Mayo",
        "Del Campillo",
        "Del Viso",
        "Despenaderos",
        "Devoto",
        "Diaz",
        "Diego de Alvear",
        "Doblas",
        "Dock Sud",
        "Dolores",
        "Don Bosco",
        "Don Torcuato",
        "Drabble",
        "Eduardo Castex",
        "El Calafate",
        "El Dorado",
        "El Hoyo",
        "El Palomar",
        "El Talar",
        "Eldorado",
        "El Trebol",
        "Embalse",
        "Empalme Lobos",
        "Ensenada",
        "Esperanza",
        "Esquel",
        "Esteban Echeverria",
        "Ezeiza",
        "Ezpeleta",
        "Famailla",
        "Fatima",
        "Federal",
        "Fernandez",
        "Firmat",
        "Florencio Varela",
        "Florentino Ameghino",
        "Flores",
        "Floresta",
        "Florida",
        "Formosa",
        "Francisco Alvarez",
        "Franck",
        "Fray Luis A. Beltran",
        "Freyre",
        "Frias",
        "Funes",
        "Gaiman",
        "Galvez",
        "Garin",
        "Garupa",
        "General Acha",
        "General Alvear",
        "General Cabrera",
        "General Deheza",
        "General Guido",
        "General Juan Madariaga",
        "General Lagos",
        "General Las Heras",
        "General Lavalle",
        "General Mansilla",
        "General Martin Miguel de Guemes",
        "General Pacheco",
        "General Paz",
        "General Pico",
        "General Roca",
        "General Rodriguez",
        "General San Martin",
        "General Viamonte",
        "General Villegas",
        "Germania",
        "Glew",
        "Gobernador Crespo",
        "Gobernador Galvez",
        "Godoy",
        "Godoy Cruz",
        "Gonzalez Catan",
        "Gonzalez Moreno",
        "Goya",
        "Granadero Baigorria",
        "Grand Bourg",
        "Gualeguay",
        "Guatrache",
        "Guernica",
        "Henderson",
        "Hernando",
        "Hersilia",
        "Hilario",
        "Hilario Ascasubi",
        "Hipatia",
        "Hipolito Yrigoyen",
        "Huanchillas",
        "Huanguelen",
        "Huinca Renanco",
        "Humahuaca",
        "Hurlingham",
        "Ibarlucea",
        "Ibicuy",
        "Independencia",
        "Ingeniero Beaugey",
        "Ingeniero Luiggi",
        "Ingeniero Maschwitz",
        "Intendente Alvear",
        "Isidro Casanova",
        "Ituzaingo",
        "James Craik",
        "Jauregui",
        "Jeppener",
        "Jesus Maria",
        "Jose Leon Suarez",
        "Jose Marmol",
        "Juan Pujol",
        "Justiniano Posse",
        "La Banda",
        "La Boca",
        "La Calera",
        "La Cumbre",
        "La Falda",
        "La Leonesa",
        "La Lucila",
        "La Madrid",
        "La Pampa",
        "La Para",
        "La Paz",
        "La Plata",
        "La Punta",
        "La Rioja",
        "La Tablada",
        "La Union",
        "La Violeta",
        "Laborde",
        "Laboulaye",
        "Laferrere",
        "Laguna Alsina",
        "Lanus",
        "Larroque",
        "Las Catitas",
        "Las Flores",
        "Las Heras",
        "Las Perdices",
        "Las Rosas",
        "Las Talitas",
        "Las Varillas",
        "Lavalle",
        "Leandro N. Alem",
        "Leones",
        "Libertad",
        "Lima",
        "Liniers",
        "Llavallol",
        "Lobos",
        "Lomas de Zamora",
        "Lomas del Mirador",
        "Longchamps",
        "Los Antiguos",
        "Los Cardales",
        "Los Molinos",
        "Los Polvorines",
        "Luis Guillon",
        "Lujan de Cuyo",
        "Luque",
        "Luzuriaga",
        "Lynch",
        "Macachin",
        "Magdalena",
        "Maggiolo",
        "Maipu",
        "Manantial",
        "Manfredi",
        "Manuel J. Cobo",
        "Maquinista Savio",
        "Mar de Ajo",
        "Mar del Plata",
        "Mar del Tuyu",
        "Marcos Juarez",
        "Marcos Paz",
        "Margarita",
        "Maria Ignacia",
        "Maria Juana",
        "Mariano Acosta",
        "Mariano J. Haedo",
        "Mariano Moreno",
        "Martinez",
        "Matheu",
        "Mayor Buratovich",
        "Melincue",
        "Mendiolaza",
        "Mendoza",
        "Mercedes",
        "Merlo",
        "Minacar",
        "Miramar",
        "Monje",
        "Monte Hermoso",
        "Monteros",
        "Montserrat",
        "Moreno",
        "Moron",
        "Morteros",
        "Muniz",
        "Munro",
        "Navarro",
        "Necochea",
        "Nogoya",
        "Nordelta",
        "Nunez",
        "Obera",
        "Oliva",
        "Oliveros",
        "Olivos",
        "Oncativo",
        "Open Door",
        "Ordonez",
        "Palermo",
        "Palmira",
        "Palpala",
        "Partido de Jose C. Paz",
        "Pasco",
        "Paso del Rey",
        "Paternal",
        "Pavon",
        "Pedernales",
        "Pedro Luro",
        "Pellegrini",
        "Perez",
        "Pergamino",
        "Perico",
        "Perito Moreno",
        "Piamonte",
        "Pico de Salamanca",
        "Pico Truncado",
        "Pigue",
        "Pilar",
        "Pinamar",
        "Piquete Cabado",
        "Platanos",
        "Plaza Huincul",
        "Plottier",
        "Pontevedra",
        "Portena",
        "Posadas",
        "Pozo del Molle",
        "Presidente Derqui",
        "Puan",
        "Pueblo San Jose",
        "Puerto Madryn",
        "Puerto Rico",
        "Pueyrredon",
        "Punta Alta",
        "Quilmes",
        "Rada Tilly",
        "Rafael Calzada",
        "Rafael Castillo",
        "Rafael Obligado",
        "Rafaela",
        "Ramallo",
        "Ramos Mejia",
        "Ranchos",
        "Rancul",
        "Ranelagh",
        "Rawson",
        "Realico",
        "Recoleta",
        "Reconquista",
        "Remedios de Escalada",
        "Resistencia",
        "Retiro",
        "Rio Ceballos",
        "Rio Colorado",
        "Rio Grande",
        "Rio Piedras",
        "Rio Segundo",
        "Rio Tercero",
        "Rivadavia",
        "Rocamora",
        "Rodriguez Pena",
        "Rojas",
        "Roldan",
        "Roque Perez",
        "Rosario",
        "Rosas",
        "Rufino",
        "Sacanta",
        "Saenz Pena",
        "Saladillo",
        "Salguero",
        "Salsipuedes",
        "Salta",
        "Salto",
        "Salto Grande",
        "Sampacho",
        "San Andres",
        "San Andres de Giles",
        "San Antonio de Areco",
        "San Antonio de Arredondo",
        "San Antonio de Obligado",
        "San Antonio de Padua",
        "San Antonio Oeste",
        "San Benito",
        "San Bernardo",
        "San Carlos de Bolivar",
        "San Cayetano",
        "San Clemente",
        "San Cristobal",
        "San Fernando",
        "San Fernando del Valle de Catamarca",
        "San Francisco",
        "San Francisco de Santa Fe",
        "San Francisco Solano",
        "San Genaro",
        "San Gregorio",
        "San Guillermo",
        "San Isidro",
        "San Isidro de Lules",
        "San Javier",
        "San Jeronimo Norte",
        "San Jorge",
        "San Jose",
        "San Jose de la Esquina",
        "San Juan",
        "San Justo",
        "San Lorenzo",
        "San Luis",
        "San Manuel",
        "San Martin",
        "San Martin de las Escobas",
        "San Miguel",
        "San Miguel del Monte",
        "San Nicolas",
        "San Pedro",
        "San Rafael",
        "San Salvador",
        "San Salvador de Jujuy",
        "San Telmo",
        "San Vicente",
        "Sanchez",
        "Santa Clara de Saguier",
        "Santa Elena",
        "Santa Fe",
        "Santa Lucia",
        "Santa Rita",
        "Santa Rosa",
        "Santa Teresita",
        "Santiago del Estero",
        "Santo Tome",
        "Santos Lugares",
        "Sarandi",
        "Sarmiento",
        "Segui",
        "Sierra de la Ventana",
        "Sierra de los Padres",
        "Sinsacate",
        "Suipacha",
        "Sunchales",
        "Tablada",
        "Tacuari",
        "Tafi Viejo",
        "Tandil",
        "Tapalque",
        "Tapiales",
        "Temperley",
        "Teodelina",
        "Thames",
        "Tigre",
        "Tio Pujio",
        "Todd",
        "Tornquist",
        "Tortuguitas",
        "Tostado",
        "Totoras",
        "Trelew",
        "Trenque Lauquen",
        "Tres Arroyos",
        "Trevelin",
        "Tristan Suarez",
        "Tunuyan",
        "Tupungato",
        "Turdera",
        "Ucacha",
        "Uriburu",
        "Ushuaia",
        "Valle Hermoso",
        "Vedia",
        "Veinticinco de Mayo",
        "Venado Tuerto",
        "Vera",
        "Veronica",
        "Viale",
        "Viamonte",
        "Vicente Lopez",
        "Victoria",
        "Vicuna Mackenna",
        "Viedma",
        "Villa Aberastain",
        "Villa Adelina",
        "Villa Allende",
        "Villa Alsina",
        "Villa Amelia",
        "Villa Angela",
        "Villa Ballester",
        "Villa Bosch",
        "Villa Canas",
        "Villa Carlos Paz",
        "Villa Constitucion",
        "Villa de Maria",
        "Villa de Mayo",
        "Villa del Parque",
        "Villa Dolores",
        "Villa Dominico",
        "Villa Elisa",
        "Villa General Belgrano",
        "Villa Gesell",
        "Villa Giardino",
        "Villa Huidobro",
        "Villa Insuperable",
        "Villa La Angostura",
        "Villa Las Rosas",
        "Villa Lugano",
        "Villa Luzuriaga",
        "Villa Madero",
        "Villa Maria Grande",
        "Villa Media Agua",
        "Villa Mercedes",
        "Villa Nueva",
        "Villa Ocampo",
        "Villa Paranacito",
        "Villa Regina",
        "Villa Robles",
        "Villa Rosa",
        "Villa Trinidad",
        "Villa Urquiza",
        "Villaguay",
        "Vuelta de Obligado",
        "Warnes",
        "Wheelwright",
        "Wilde",
        "Winifreda",
        "Yerba Buena",
        "Zenon Pereyra",
      ],
    },
    {
      iso2: "CL",
      iso3: "CHL",
      country: "Chile",
      currency: "CLP",
      symbol: "$",
      cities: [
        "Algarrobo",
        "Angol",
        "Antofagasta",
        "Apoquindo",
        "Arauco",
        "Arica",
        "Buin",
        "Bulnes",
        "Calama",
        "Caldera",
        "Castro",
        "Catemu",
        "Centro",
        "Cerrillos de Tamaya",
        "Chicureo Abajo",
        "Chiguayante",
        "Chillan",
        "Chillan Viejo",
        "Chimbarongo",
        "Chonchi",
        "Chuquicamata",
        "Coihaique",
        "Colina",
        "Collipulli",
        "Concon",
        "Constitucion",
        "Coquimbo",
        "Coronel",
        "Cunco",
        "Curacavi",
        "Dalcahue",
        "El Arco",
        "El Bosque",
        "El Monte",
        "El Quisco",
        "El Salto",
        "El Salvador",
        "El Valle",
        "Fresia",
        "Galvarino",
        "Graneros",
        "Hanga Roa",
        "Iquique",
        "La Calera",
        "La Cisterna",
        "La Granja",
        "La Laja",
        "La Ligua",
        "La Reina",
        "La Serena",
        "La Union",
        "Lampa",
        "Las Condes",
        "Lautaro",
        "Llanquihue",
        "Lo Barnechea",
        "Lolol",
        "Los Andes",
        "Los Angeles",
        "Machali",
        "Macul",
        "Maipu",
        "Maquina Atacama",
        "Maule",
        "Mejillones",
        "Melipilla",
        "Miraflores",
        "Molina",
        "Monte Aguila",
        "Nacimiento",
        "Nogales",
        "Nunoa",
        "Olmue",
        "Osorno",
        "Ovalle",
        "Paillaco",
        "Penablanca",
        "Penaflor",
        "Port Montt",
        "Providencia",
        "Puchuncavi",
        "Pucon",
        "Puente Alto",
        "Puerto Aisen",
        "Puerto Natales",
        "Puerto Varas",
        "Punta Arenas",
        "Puren",
        "Purranque",
        "Quellon",
        "Quemchi",
        "Quilicura",
        "Quillota",
        "Rancagua",
        "Recoleta",
        "Renaca",
        "Renca",
        "Rengo",
        "Rinconada",
        "Rio Bueno",
        "San Antonio",
        "San Bernardo",
        "San Carlos",
        "San Felipe",
        "San Fernando",
        "San Javier",
        "San Martin",
        "San Pedro",
        "Santa Barbara",
        "Santiago",
        "Talagante",
        "Talca",
        "Talcahuano",
        "Tarapaca",
        "Temuco",
        "Tome",
        "Valdivia",
        "Vallenar",
        "Villa Alemana",
        "Villarrica",
        "Vitacura",
      ],
    },
    {
      iso2: "CO",
      iso3: "COL",
      country: "Colombia",
      currency: "COP",
      symbol: "$",
      cities: citiesColombia.map((el) => el),
    },
    {
      iso2: "EC",
      iso3: "ECU",
      country: "Ecuador",
      currency: "USD",
      symbol: "U$S",
      cities: [
        "Alausí",
        "Ambato",
        "Archidona",
        "Atacames",
        "Atuntaqui",
        "Azogues",
        "Babahoyo",
        "Bahía de Caráquez",
        "Balzar",
        "Baños",
        "Catamayo",
        "Cayambe",
        "Chone",
        "Cuenca",
        "Daule",
        "El Chaco",
        "Eloy Alfaro",
        "Esmeraldas",
        "Guaranda",
        "Guayaquil",
        "Huaquillas",
        "Ibarra",
        "Jipijapa",
        "Junín",
        "La Concordia",
        "La Maná",
        "La Troncal",
        "Latacunga",
        "Llacao",
        "Loja",
        "Lomas de Sargentillo",
        "Macará",
        "Macas",
        "Machala",
        "Manta",
        "Milagro",
        "Montecristi",
        "Muisne",
        "Naranjal",
        "Naranjito",
        "Nueva Loja",
        "Otavalo",
        "Pasaje",
        "Pedernales",
        "Pedro Carbo",
        "Pedro Vicente Maldonado",
        "Pelileo",
        "Piñas",
        "Portoviejo",
        "Puerto Ayora",
        "Puerto Baquerizo Moreno",
        "Puerto Francisco de Orellana",
        "Puerto Quito",
        "Puyo",
        "Píllaro",
        "Quevedo",
        "Quito",
        "Riobamba",
        "Rosa Zarate",
        "Salinas",
        "Samborondón",
        "San Gabriel",
        "San Jacinto de Buena Fe",
        "San Lorenzo de Esmeraldas",
        "San Miguel de Salcedo",
        "Sangolquí",
        "Santa Cruz",
        "Santa Elena",
        "Santa Rosa",
        "Santo Domingo de los Colorados",
        "Tena",
        "Tosagua",
        "Tulcán",
        "Valdez",
        "Valencia",
        "Velasco Ibarra",
        "Ventanas",
        "Vinces",
        "Yaguachi Nuevo",
        "Zamora",
      ],
    },
    {
      iso2: "PE",
      iso3: "PER",
      country: "Peru",
      currency: "PEN",
      symbol: "S/",
      cities: [
        "Abancay",
        "Arequipa",
        "Ate",
        "Ayacucho",
        "Bagua",
        "Barranca",
        "Barranco",
        "Bellavista",
        "Bolivar",
        "Cajamarca",
        "Callao",
        "Calle",
        "Caras",
        "Cerro de Pasco",
        "Chachapoyas",
        "Chiclayo",
        "Chimbote",
        "Chincha",
        "Cusco",
        "Cuzco",
        "El Agustino",
        "Hacienda La Palma",
        "Huacho",
        "Huancavelica",
        "Huancayo",
        "Huaral",
        "Huaraz",
        "Huaytara",
        "Ica",
        "Ilo",
        "Imperial",
        "Iquitos",
        "Jaen",
        "Jesus Maria",
        "Jose Olaya",
        "Juliaca",
        "Junin",
        "La Molina",
        "La Perla",
        "La Punta",
        "Lambayeque",
        "Lima",
        "Lince",
        "Loreto",
        "Lurigancho",
        "Machu Picchu",
        "Maldonado",
        "Minas de Marcona",
        "Miraflores",
        "Moquegua",
        "Moyobamba",
        "Pasco",
        "Paucarpata",
        "Pimentel",
        "Pisco",
        "Piura",
        "Progreso",
        "Pucallpa",
        "Puerto Inca",
        "Puerto Maldonado",
        "Puno",
        "Rimac",
        "Rioja",
        "San Borja",
        "San Isidro",
        "San Juan Bautista",
        "San Martin",
        "San Miguel",
        "Santa",
        "Santiago",
        "Santiago De Surco",
        "Sullana",
        "Surco",
        "Surquillo",
        "Tacna",
        "Talara",
        "Tarapoto",
        "Tingo Maria",
        "Trujillo",
        "Tumbes",
        "Ventanilla",
        "Victoria",
      ],
    },
  ],
};
